version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes: 
      - cache:/data
    environment:
      - REDIS_ARGS="--notify-keyspace-events KEx"

volumes:
  cache:
