// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: metrics.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace OpenTelemetry.Proto.Metrics.V1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MetricsData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource_metrics")]
        public global::System.Collections.Generic.List<ResourceMetrics> ResourceMetrics { get; } = new global::System.Collections.Generic.List<ResourceMetrics>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceMetrics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource")]
        public global::OpenTelemetry.Proto.Resource.V1.Resource Resource { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scope_metrics")]
        public global::System.Collections.Generic.List<ScopeMetrics> ScopeMetrics { get; } = new global::System.Collections.Generic.List<ScopeMetrics>();

        [global::ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScopeMetrics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scope")]
        public global::OpenTelemetry.Proto.Common.V1.InstrumentationScope Scope { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"metrics")]
        public global::System.Collections.Generic.List<Metric> Metrics { get; } = new global::System.Collections.Generic.List<Metric>();

        [global::ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Metric : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"unit")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Unit { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"gauge")]
        public Gauge Gauge
        {
            get => __pbn__data.Is(5) ? ((Gauge)__pbn__data.Object) : default;
            set => __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeGauge() => __pbn__data.Is(5);
        public void ResetGauge() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 5);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__data;

        [global::ProtoBuf.ProtoMember(7, Name = @"sum")]
        public Sum Sum
        {
            get => __pbn__data.Is(7) ? ((Sum)__pbn__data.Object) : default;
            set => __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeSum() => __pbn__data.Is(7);
        public void ResetSum() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 7);

        [global::ProtoBuf.ProtoMember(9, Name = @"histogram")]
        public Histogram Histogram
        {
            get => __pbn__data.Is(9) ? ((Histogram)__pbn__data.Object) : default;
            set => __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
        }
        public bool ShouldSerializeHistogram() => __pbn__data.Is(9);
        public void ResetHistogram() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 9);

        [global::ProtoBuf.ProtoMember(10, Name = @"exponential_histogram")]
        public ExponentialHistogram ExponentialHistogram
        {
            get => __pbn__data.Is(10) ? ((ExponentialHistogram)__pbn__data.Object) : default;
            set => __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
        }
        public bool ShouldSerializeExponentialHistogram() => __pbn__data.Is(10);
        public void ResetExponentialHistogram() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 10);

        [global::ProtoBuf.ProtoMember(11, Name = @"summary")]
        public Summary Summary
        {
            get => __pbn__data.Is(11) ? ((Summary)__pbn__data.Object) : default;
            set => __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(11, value);
        }
        public bool ShouldSerializeSummary() => __pbn__data.Is(11);
        public void ResetSummary() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 11);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Gauge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_points")]
        public global::System.Collections.Generic.List<NumberDataPoint> DataPoints { get; } = new global::System.Collections.Generic.List<NumberDataPoint>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Sum : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_points")]
        public global::System.Collections.Generic.List<NumberDataPoint> DataPoints { get; } = new global::System.Collections.Generic.List<NumberDataPoint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"aggregation_temporality")]
        public AggregationTemporality AggregationTemporality { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_monotonic")]
        public bool IsMonotonic { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Histogram : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_points")]
        public global::System.Collections.Generic.List<HistogramDataPoint> DataPoints { get; } = new global::System.Collections.Generic.List<HistogramDataPoint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"aggregation_temporality")]
        public AggregationTemporality AggregationTemporality { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExponentialHistogram : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_points")]
        public global::System.Collections.Generic.List<ExponentialHistogramDataPoint> DataPoints { get; } = new global::System.Collections.Generic.List<ExponentialHistogramDataPoint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"aggregation_temporality")]
        public AggregationTemporality AggregationTemporality { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Summary : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data_points")]
        public global::System.Collections.Generic.List<SummaryDataPoint> DataPoints { get; } = new global::System.Collections.Generic.List<SummaryDataPoint>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NumberDataPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"as_double")]
        public double AsDouble
        {
            get => __pbn__value.Is(4) ? __pbn__value.Double : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64(4, value);
        }
        public bool ShouldSerializeAsDouble() => __pbn__value.Is(4);
        public void ResetAsDouble() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__value, 4);

        private global::ProtoBuf.DiscriminatedUnion64 __pbn__value;

        [global::ProtoBuf.ProtoMember(6, Name = @"as_int", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public long AsInt
        {
            get => __pbn__value.Is(6) ? __pbn__value.Int64 : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64(6, value);
        }
        public bool ShouldSerializeAsInt() => __pbn__value.Is(6);
        public void ResetAsInt() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__value, 6);

        [global::ProtoBuf.ProtoMember(5, Name = @"exemplars")]
        public global::System.Collections.Generic.List<Exemplar> Exemplars { get; } = new global::System.Collections.Generic.List<Exemplar>();

        [global::ProtoBuf.ProtoMember(8, Name = @"flags")]
        public uint Flags { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HistogramDataPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(9, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Count { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sum")]
        public double Sum
        {
            get => __pbn__Sum.GetValueOrDefault();
            set => __pbn__Sum = value;
        }
        public bool ShouldSerializeSum() => __pbn__Sum != null;
        public void ResetSum() => __pbn__Sum = null;
        private double? __pbn__Sum;

        [global::ProtoBuf.ProtoMember(6, Name = @"bucket_counts", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsPacked = true)]
        public ulong[] BucketCounts { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"explicit_bounds", IsPacked = true)]
        public double[] ExplicitBounds { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"exemplars")]
        public global::System.Collections.Generic.List<Exemplar> Exemplars { get; } = new global::System.Collections.Generic.List<Exemplar>();

        [global::ProtoBuf.ProtoMember(10, Name = @"flags")]
        public uint Flags { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"min")]
        public double Min
        {
            get => __pbn__Min.GetValueOrDefault();
            set => __pbn__Min = value;
        }
        public bool ShouldSerializeMin() => __pbn__Min != null;
        public void ResetMin() => __pbn__Min = null;
        private double? __pbn__Min;

        [global::ProtoBuf.ProtoMember(12, Name = @"max")]
        public double Max
        {
            get => __pbn__Max.GetValueOrDefault();
            set => __pbn__Max = value;
        }
        public bool ShouldSerializeMax() => __pbn__Max != null;
        public void ResetMax() => __pbn__Max = null;
        private double? __pbn__Max;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExponentialHistogramDataPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Count { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sum")]
        public double Sum
        {
            get => __pbn__Sum.GetValueOrDefault();
            set => __pbn__Sum = value;
        }
        public bool ShouldSerializeSum() => __pbn__Sum != null;
        public void ResetSum() => __pbn__Sum = null;
        private double? __pbn__Sum;

        [global::ProtoBuf.ProtoMember(6, Name = @"scale", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Scale { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"zero_count", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ZeroCount { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"positive")]
        public Buckets Positive { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"negative")]
        public Buckets Negative { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"flags")]
        public uint Flags { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"exemplars")]
        public global::System.Collections.Generic.List<Exemplar> Exemplars { get; } = new global::System.Collections.Generic.List<Exemplar>();

        [global::ProtoBuf.ProtoMember(12, Name = @"min")]
        public double Min
        {
            get => __pbn__Min.GetValueOrDefault();
            set => __pbn__Min = value;
        }
        public bool ShouldSerializeMin() => __pbn__Min != null;
        public void ResetMin() => __pbn__Min = null;
        private double? __pbn__Min;

        [global::ProtoBuf.ProtoMember(13, Name = @"max")]
        public double Max
        {
            get => __pbn__Max.GetValueOrDefault();
            set => __pbn__Max = value;
        }
        public bool ShouldSerializeMax() => __pbn__Max != null;
        public void ResetMax() => __pbn__Max = null;
        private double? __pbn__Max;

        [global::ProtoBuf.ProtoMember(14, Name = @"zero_threshold")]
        public double ZeroThreshold { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Buckets : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"offset", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
            public int Offset { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"bucket_counts", IsPacked = true)]
            public ulong[] BucketCounts { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SummaryDataPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Count { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sum")]
        public double Sum { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"quantile_values")]
        public global::System.Collections.Generic.List<ValueAtQuantile> QuantileValues { get; } = new global::System.Collections.Generic.List<ValueAtQuantile>();

        [global::ProtoBuf.ProtoMember(8, Name = @"flags")]
        public uint Flags { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ValueAtQuantile : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"quantile")]
            public double Quantile { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value")]
            public double Value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Exemplar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"filtered_attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> FilteredAttributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(2, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"as_double")]
        public double AsDouble
        {
            get => __pbn__value.Is(3) ? __pbn__value.Double : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64(3, value);
        }
        public bool ShouldSerializeAsDouble() => __pbn__value.Is(3);
        public void ResetAsDouble() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__value, 3);

        private global::ProtoBuf.DiscriminatedUnion64 __pbn__value;

        [global::ProtoBuf.ProtoMember(6, Name = @"as_int", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public long AsInt
        {
            get => __pbn__value.Is(6) ? __pbn__value.Int64 : default;
            set => __pbn__value = new global::ProtoBuf.DiscriminatedUnion64(6, value);
        }
        public bool ShouldSerializeAsInt() => __pbn__value.Is(6);
        public void ResetAsInt() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__value, 6);

        [global::ProtoBuf.ProtoMember(4, Name = @"span_id")]
        public byte[] SpanId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AggregationTemporality
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_UNSPECIFIED")]
        AggregationTemporalityUnspecified = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_DELTA")]
        AggregationTemporalityDelta = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATION_TEMPORALITY_CUMULATIVE")]
        AggregationTemporalityCumulative = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DataPointFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"FLAG_NONE")]
        FlagNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FLAG_NO_RECORDED_VALUE")]
        FlagNoRecordedValue = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
